src/FastMCP.test.ts
src/FastMCP.ts

Fixes #1
Update `setupToolHandlers` method to throw `ErrorCode.InvalidParams` if tool parameters do not match the zod schema.
* **src/FastMCP.ts**
- Change error code from `ErrorCode.InvalidRequest` to `ErrorCode.InvalidParams`.
- Update error message to "Invalid {tool name} parameters".
* **src/FastMCP.test.ts**
- Add test to check for `ErrorCode.InvalidParams` when tool parameters do not match the zod schema.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/punkpeye/fastmcp/pull/5?shareId=48b23eae-bbe2-4c68-8f79-eed7ffaa13a1).

Throw ErrorCode.InvalidParams if tool params do not match zod schema

---

src/FastMCP.ts

Hey! I'm working on a docs MCP for Mastra.ai (https://github.com/mastra-ai/mastra/pull/2966) and ran into the issue that it doesn't work in Cursor.
Seems the issue is we need to check if the client supports listing roots changes, not just if it supports roots.
I'm not 100% sure about the change so interested to hear your thoughts. If I do a try/catch here without checking for `roots.listChanges` that also works. Any idea the difference between the client supporting roots vs the client supporting roots.listChanges?
Fixes https://github.com/punkpeye/fastmcp/issues/19

fix: Cursor errors when listing roots

---

README.md
package.json
pnpm-lock.yaml
src/FastMCP.ts
src/examples/addition.ts

This PR replaces direct Zod usage with Standard Schema support, allowing users to choose their preferred validation library while maintaining existing functionality.
- Added `@standard-schema/spec` and `xsschema` dependencies
- Updated `ToolParameters` type to use `StandardSchemaV1`
- Replaced `zodToJsonSchema` with `toJsonSchema`
- Users can now use any schema library that implements Standard Schema (Zod, Valibot, ArkType)
- Aligns with ecosystem direction supported by schema library creators
- Follows the example of libraries like tRPC, TanStack Form, and others adopting Standard Schema
Resolves #26

Switch from Zod to Standard Schema

---

README.md

If I didn't `pnpm build`, the following error occurred.
```
$ npx fastmcp dev src/examples/addition.ts
'fastmcp' is not recognized as an internal or external command, operable program or batch file.
```
I think we should build it in advance, so I fix README.

Update local test procedures

---

src/FastMCP.ts

Add the MCP Optional instructions option describing how to use the server and its features.
From the underlying server options of the `@modelcontextprovider/sdk`
```ts
export type ServerOptions = ProtocolOptions & {
/**
* Capabilities to advertise as being supported by this server.
*/
capabilities?: ServerCapabilities;
/**
* Optional instructions describing how to use the server and its features.
*/
instructions?: string;
};
```

Add the MCP Optional instructions option

---

README.md

Fixed the typo. The type of the `request` is `http.IncomingMessage`, so it's `request` instead of `{request}`.

fix: typo Update README.md

---

README.md
src/FastMCP.test.ts
src/FastMCP.ts
src/examples/addition.ts

Add ping configuration to `ServerOptions` to reduce excessive logging and improve connection handling. Enable pings by default for SSE/HTTP Streaming while disabling for `stdio`. Allow customization of ping interval and log level
Close #50

feat: configurable ping behavior

---

README.md
src/FastMCP.test.ts
src/FastMCP.ts

- Add a configurable health check endpoint for HTTP Stream transport
- Add comprehensive documentation for the health check feature in README.md
This PR adds a new feature to FastMCP that enables a configurable health check endpoint when using the HTTP Stream transport. This is useful for load balancers, container orchestration systems, and monitoring tools to verify the server's health.
- Added a new `health` configuration option to `ServerOptions` with the following customizable parameters:
- `enabled`: Toggle the health endpoint (default: true)
- `path`: HTTP path to respond to (default: "/health")
- `status`: HTTP status code to return (default: 200)
- `message`: Plain-text response body (default: "ok")
- Implemented the endpoint handler in the HTTP Stream transport's …

feat: add support for health endpoint

---

package.json
pnpm-lock.yaml
src/FastMCP.test.ts

- added failing test
- pinned `xsschema` version to latest 0.3.0-beta.1 version (see comment below)

fix: Resolve tool crashing from use with Zod v4

---

src/FastMCP.ts

Resolves typing issue where `required` and `complete` properties cannot be used together in ResourceTemplate arguments, bringing type consistency with PromptArgument interface.
Closes #20

fix: ResourceTemplate Arguments Type

---

README.md
src/FastMCP.test.ts
src/FastMCP.ts
src/examples/addition.ts

Implements the embedded resources API, providing **a clean and simple way to include resources in tool responses** without ~code~ code duplication:
```ts
// Example usage
server.addTool({
name: "get_user_data",
execute: async (args) => {
return {
content: [{
type: "resource",
resource: await server.embedded(`user://profile/${args.userId}`)
}]
};
}
});
```
Closes #85

feat: embedded resources API (`server.embedded(uri)` method)

---

src/FastMCP.test.ts
src/FastMCP.ts
src/examples/addition.ts

When using FastMCP with HTTP Stream transport, progress notifications (`reportProgress`) and streaming content (`streamContent`) were not sent immediately to clients. Instead, they were buffered by the HTTP transport layer and only flushed when the next async operation occurred. So, we're added automatic flush behavior to both `reportProgress` and `streamContent` functions by inserting a minimal async operation after each notification:
```ts
// Force flush for HTTP stream transport to prevent buffering delays
await new Promise((resolve) => setImmediate(resolve));
```
- `setImmediate` schedules the callback for the next iteration of the event loop
- This gives Node.js time to flush any buffered HTTP responses
- The operation is lightweight and doesn't introduce significant delay
- It's …

fix: HTTP Stream Transport Buffering

---

README.md
src/FastMCP.test.ts
src/FastMCP.ts

Add optional endpoint attribute to specific which endpoint to use for mcp server (default to "/mcp")
#95 
```typescript
await server.start({
httpStream: {
port: 8080,
endpoint: "/custom-mcp",
},
transportType: "httpStream",
});
```

feat: Add support to change http server endpoint

---

src/FastMCP.test.ts
src/FastMCP.ts

Makes a few changes:
- `addResourceTemplate.load` allows returning an array of resources (similar to `addResource.load`)
- Allows `ResourceTemplate.load` resource results to specify optional mimeType and uri
- useful when ResourceTemplate will return a list of different resources, e.g. returning all files in a directory
- uses `satisfies` keyword to type-check return types of ResourceTemplates/Resources against the types of the MCP SDK

feat: Allow ResourceTemplate to return array of resources.

---

README.md
src/FastMCP.ts

Solves https://github.com/punkpeye/fastmcp/issues/122
Note: for some reason I wasn't able to import the RequestOptions from the protocol file

feat: add support for passing options to requestSampling

---

src/FastMCP.ts

Implements **parameterless server startup** with auto-configuration that:
- Automatically parses CLI arguments (`--transport`, `--port`, `--endpoint`)
- Reads environment variables (`FASTMCP_TRANSPORT`, `FASTMCP_PORT`, `FASTMCP_ENDPOINT`)
- Applies smart configuration precedence
- Eliminates boilerplate while maintaining flexibility
```ts
server.start(); // Auto-detects from CLI/environment
```
Configuration Precedence:
1. **Explicit parameters** (highest priority)
2. **CLI arguments** (`--transport http-stream --port 3000`)
3. **Environment variables** (`FASTMCP_TRANSPORT=httpStream`)
4. **Sensible defaults** (stdio transport)
Explicit Override (**unchanged**):
```ts
server.start({
transportType: "httpStream",
httpStream: { port: 3000 },
}); // still works exactly as before
```
---
Also, …

feat: Implement Parameterless `server.start()` with CLI-Based Auto-Configuration

---

README.md
src/FastMCP.oauth.test.ts
src/FastMCP.ts
src/examples/oauth-server.ts

This allows protecting a fastmcp server behind an oauth server.
This is done by adding support for OAuth 2.1 well-known discovery endpoints to FastMCP, enabling MCP servers to serve OAuth metadata for authorization flows as required by MCP Specifications 2025-03-26 and 2025-06-18.
Note that additional features could be built on top of this like token verification, scope checks, and so on. This PR adds the minimum to allow mcp developers to add support for oauth auth.
```
const server = new FastMCP({
name: "My Server",
version: "1.0.0",
oauth: {
enabled: true,
authorizationServer: {
issuer: "https://auth.example.com",
authorizationEndpoint: "https://auth.example.com/oauth/authorize",
tokenEndpoint: "https://auth.example.com/oauth/token",
responseTypesSupported: ["code"],
}, …
```

Support for .well-known oauth discovery endpoints

---

README.md
src/FastMCP.ts
src/examples/custom-logger.ts

When using FastMCP we found we wanted to redirect its console logs to our own logger, so I've had a stab at implementing that
Ran lint
Ran tests
Added to README

Add custom logger and example

---

src/FastMCP.session-context.test.ts
src/FastMCP.ts
src/examples/session-context.ts

the authentication flow in FastMCP was only being executed for HTTP transport, but was skipped entirely for stdio transport. this caused the session context to be undefined when tools were executed via stdio, even when an authenticate function was provided in the server configuration.
closes #144

fix: session context undefined in stdio transport (#144)

---

src/FastMCP.test.ts
src/FastMCP.ts

This PR allows users to host their applications on a custom path. This was a simple plumbing exercise, as `startHTTPServer` accepts a host parameter.
A unit test was added to test this, and I have used it in multiple projects.

feat: Support custom host path

---

src/FastMCP.ts

This PR is a follow-up to https://github.com/punkpeye/fastmcp/pull/39

fix: missing instructions for all transports
